package db.greendao.dznews;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import db.greendao.dznews.News;
import db.greendao.dznews.NewsDetail;

import db.greendao.dznews.NewsDao;
import db.greendao.dznews.NewsDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsDaoConfig;
    private final DaoConfig newsDetailDaoConfig;

    private final NewsDao newsDao;
    private final NewsDetailDao newsDetailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsDaoConfig = daoConfigMap.get(NewsDao.class).clone();
        newsDaoConfig.initIdentityScope(type);

        newsDetailDaoConfig = daoConfigMap.get(NewsDetailDao.class).clone();
        newsDetailDaoConfig.initIdentityScope(type);

        newsDao = new NewsDao(newsDaoConfig, this);
        newsDetailDao = new NewsDetailDao(newsDetailDaoConfig, this);

        registerDao(News.class, newsDao);
        registerDao(NewsDetail.class, newsDetailDao);
    }
    
    public void clear() {
        newsDaoConfig.getIdentityScope().clear();
        newsDetailDaoConfig.getIdentityScope().clear();
    }

    public NewsDao getNewsDao() {
        return newsDao;
    }

    public NewsDetailDao getNewsDetailDao() {
        return newsDetailDao;
    }

}
