package db.greendao.dznews;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NEWS".
 */
public class News {

    private Long id;
    private Integer article_id;
    private String title;
    private String date;
    private String intro;
    private String topic;
    private Integer view_num;
    private Integer comment_num;
    private String source;
    private String source_link;
    private Integer hot;
    private Integer pushed;

    public News() {
    }

    public News(Long id) {
        this.id = id;
    }

    public News(Long id, Integer article_id, String title, String date, String intro, String topic, Integer view_num, Integer comment_num, String source, String source_link, Integer hot, Integer pushed) {
        this.id = id;
        this.article_id = article_id;
        this.title = title;
        this.date = date;
        this.intro = intro;
        this.topic = topic;
        this.view_num = view_num;
        this.comment_num = comment_num;
        this.source = source;
        this.source_link = source_link;
        this.hot = hot;
        this.pushed = pushed;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getArticle_id() {
        return article_id;
    }

    public void setArticle_id(Integer article_id) {
        this.article_id = article_id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public String getTopic() {
        return topic;
    }

    public void setTopic(String topic) {
        this.topic = topic;
    }

    public Integer getView_num() {
        return view_num;
    }

    public void setView_num(Integer view_num) {
        this.view_num = view_num;
    }

    public Integer getComment_num() {
        return comment_num;
    }

    public void setComment_num(Integer comment_num) {
        this.comment_num = comment_num;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getSource_link() {
        return source_link;
    }

    public void setSource_link(String source_link) {
        this.source_link = source_link;
    }

    public Integer getHot() {
        return hot;
    }

    public void setHot(Integer hot) {
        this.hot = hot;
    }

    public Integer getPushed() {
        return pushed;
    }

    public void setPushed(Integer pushed) {
        this.pushed = pushed;
    }

}
